### ISSUE TITLE
Not showing media name

### ISSUE THREAD

**Issue by alexboutros** [Ombrelin/plex-rich-presence#61] opened 2021-09-19 06:02 UTC
Running the latest version (Github releases says 1.7, but it installs 1.6). Discord just says playing Plex and a timer that doesn't seem to match up with what's playing.

**Comment by Ombrelin** [comment] 2021-09-20 06:22
That's odd, I'll try to reproduce

**Comment by alexcomo95** [comment] 2021-12-12 04:10
Duplicate of #58

**Comment by Ombrelin** [comment] 2022-01-17 14:16
Closed as duplicate of #58

**Closed by Ombrelin** 2022-01-17 14:16 UTC
Labels: bug
