### ISSUE TITLE
Unable to sign in on beta

### ISSUE THREAD

**Issue by c1sxr0bzn** [Ombrelin/plex-rich-presence#74] opened 2022-10-08 13:52 UTC
GUI crashes when trying to sign in, sign in using web browser does not work either.

**Comment by PsychoManiac189** [comment] 2022-10-08 21:41
I have the same issue.

**Comment by Ombrelin** [comment] 2022-10-09 07:31
Hi, sorry to hear that. What platform are you on ?

**Comment by VeikkoLehmuskorpi** [comment] 2022-10-09 09:38
Neither of the login methods work for me either.

> Edition	Windows 10 Pro
> Version	21H2
> Installed on	‎9/‎4/‎2021
> OS build	19044.2006
> Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by Ombrelin** [comment] 2022-10-09 15:01
@VeikkoLehmuskorpi, good news, I could reproduce and fix the problem with the web login in the last release
Regarding @c1sxr0bzn's problem, I could not reproduce, but I implemented logging to file in the last release. Could you reproduce the issue, and send me the `logs.txt` file in the `.plexrichpresence` in your user directory ? Thanks in advance

**Comment by PsychoManiac189** [comment] 2022-10-10 01:03
Hi. I am able to log in via browser now, but now when the app loads it just closes right away. I can't find the logs.txt file because i cant find the .plexrichpresence folder. 
Im running 
Windows 10 Home 21H2
OS build 19044.2006
Windows Feature Experience Pack 120.2212.4180.0

**Comment by VeikkoLehmuskorpi** [comment] 2022-10-10 14:42
@PsychoManiac189 you should remove that attachment.

**Comment by PsychoManiac189** [comment] 2022-10-10 23:52
> @PsychoManiac189 you should remove that attachment.

i did, but why?

**Comment by VeikkoLehmuskorpi** [comment] 2022-10-11 14:16
@PsychoManiac189 it contains sensitive information, you shouldn't post the entire log file in public

**Comment by Ombrelin** [comment] 2022-10-11 17:46
Yeah sorry, I shouln't have logged IP address, will remove it in next version

**Comment by Ombrelin** [comment] 2022-10-12 20:06
@PsychoManiac189 your issue was most likely #78 , should be fixed in last release
@VeikkoLehmuskorpi You can safely post logs from the last release, I removed logging of IP adresse

**Comment by PsychoManiac189** [comment] 2022-10-13 01:19
> @PsychoManiac189 your issue was most likely #78 , should be fixed in last release @VeikkoLehmuskorpi You can safely post logs from the last release, I removed logging of IP adresse

ok. its working. any chance you gonna add it to say that discord is connected like the old one? also it dont show the time left on discord. just says "0:00 left"

**Comment by Ombrelin** [comment] 2022-10-21 20:11
@PsychoManiac189 this issue is tracked by #77. I will close this one, for now, @c1sxr0bzn @VeikkoLehmuskorpi don't hesitate to reopen and post logs if you still encounter this problem

**Closed by Ombrelin** 2022-10-21 20:11 UTC
