### ISSUE TITLE
Remaining song runtime not being displayed

### ISSUE THREAD

**Issue by AlmondManttv** [Ombrelin/plex-rich-presence#77] opened 2022-10-09 16:42 UTC
Using the Beta (2.0.1)
The time remaining for the song is displayed as "00 min 00 s", which seems off since the song is currently running and has time left.

Using Plexamp

**Comment by Ombrelin** [comment] 2022-10-09 17:24
Could you upload the `logs.txt` file which should be in a `.plexrichpresence` in your user directory ?

**Comment by AlmondManttv** [comment] 2022-10-09 17:27
[logs.txt](https://github.com/Ombrelin/plex-rich-presence/files/9742197/logs.txt)

**Comment by Ombrelin** [comment] 2022-10-09 17:55
Mmmh, seeing nothing odd in the log regarding the time ; I'll try to reproduce with plexamp and keep you posted

**Comment by CalebSnell** [comment] 2022-10-09 23:43
Hello! I have this same issue but using the plex desktop app. The Plex Rich Presence app connects by public IP (auto detected) and port 32400, which is appropriately port forwarded w/ NAT loopback. I attached a few lines from the logs.txt file, public IP changed to X.X.X.X. Let me know if you need any other info. 
[logs.txt](https://github.com/Ombrelin/plex-rich-presence/files/9742773/logs.txt)

**Comment by PsychoManiac189** [comment] 2022-10-15 21:18
This same thing is happening when watching movies. it shows 0:00 for the time remaining

**Comment by Janniqz** [comment] 2022-10-17 09:52
Experiencing something similar. Instead of showing 0:00 it constantly hovers somewhere around 2 hours though.

It seems like the displayed time doesn't take Timezones into account. Switching from CEST (+2) to normal UTC (+0) at least brings it down to a few minutes. The remainder is roughly correct but likes to jump around.

https://user-images.githubusercontent.com/964321/196147127-6bcf981a-5b0e-4d04-8705-d723af7bc517.mp4

[logs.txt](https://github.com/Ombrelin/plex-rich-presence/files/9799207/logs.txt)

**Comment by Janniqz** [comment] 2022-10-17 11:19
The second Issue seems to be related to Discord and the ViewOffset from PLEX. Whilst the song is still playing the returned ViewOffset sometimes returns the same value.

Discord on the other hand automatically counts down from whatever Timestamp it's given. Technically the Timestamp would only need to be provided once and Discord does the rest but this wouldn't account for jumping forward within what's being played...

**Comment by Ombrelin** [comment] 2022-10-21 20:09
@Janniqz thanks you for your contribution and this insightfull information about this problem. I'll investigate and try to find a fix for this issue maybe by updating the timestamp in discord only when its has changed based on a cached value.

**Closed** 2022-12-25 10:23 UTC
Labels: bug
