### ISSUE TITLE
Remote RPC for Discord user

### ISSUE THREAD

**Issue by Soitora** [Ombrelin/plex-rich-presence#82] opened 2022-10-25 11:28 UTC
I tried searching Issues/PR/Wikis

Any possibility for us to do remote RPC through inputting our Discord token?
I watch Plex on my TV, and when I do my PC is off, but my Windows server PC is always on

So I'd like the ability to have it function without installing Discord to that server PC

**Comment by Ombrelin** [comment] 2022-10-25 14:06
Hi @Soitora,
This is a whole new use case, but I agree that it's interesting.
The use case was raised on #56. Some resources were shared on the subject on yhis thread.

**Comment by Soitora** [comment] 2022-10-25 17:07
Unfortunately I am not aware of any specific thing for this, I had also searched for Discord remote RPC and stumbled upon the DiscordJS resource

**Comment by Ombrelin** [comment] 2022-10-25 18:10
First, DiscordJS is an a library for nodejs which is analoguous to what is used in the app (https://github.com/Lachee/discord-rpc-csharp).
Anyway, to enable rich presence, you must have discord running somewhere. The use case of running Plex Rich Presence on a server is possible, for instance in docker : https://github.com/davidk/docker-discord.

I'm going to close this for now, as duplicate of #56. Don't hesitate to re-open if you come up with a different solution from what planned in #56, a CLI version of the app which could be used easly in a server environment.

**Closed by Ombrelin** 2022-10-25 18:10 UTC
