### ISSUE TITLE
 "Display idle status" not preserved between program restarts

### ISSUE THREAD

**Issue by nonamethanks** [Ombrelin/plex-rich-presence#88] opened 2022-11-27 18:05 UTC
To disable "Display idle status" you currently have to turn it off every time the program starts. The setting should be saved instead.

**Comment by Ombrelin** [comment] 2022-11-27 18:17
Hi, thank you for reporting this. Indeed I had intended it to be persisted. But seemingly there's am issue with that. Will investigate.

**Comment by Ombrelin** [comment] 2022-12-03 15:17
Sould be fixed

**Comment by nonamethanks** [comment] 2022-12-03 15:29
Nope @Ombrelin it still doesn't save it. Also the installer version for the latest release from [here](https://github.com/Ombrelin/plex-rich-presence/releases/tag/2.0.6) still says 2.0.31 on the window name when you open it, and the deb file says 2.0.5, not sure if those are connected.

**Comment by Ombrelin** [comment] 2022-12-03 17:38
Yes I got the version numbers wrong (forgot to update them, I should do it automatically in CI) but as long as you updated for release 2.0.6, it should work.

**Comment by nonamethanks** [comment] 2022-12-03 17:39
I updated, but when I close the app the setting is still automatically enabled even if it was disabled when I closed it.

**Comment by Ombrelin** [comment] 2022-12-03 19:17
Mmmh I can't reproduce with the last version 🤔
Could you tell me the value of the `enableIdleStatus` key in the JSON file under your_user_directory/.plexrichpresence ?

**Comment by nonamethanks** [comment] 2022-12-03 19:19
There's no file under %userprofile%/.plexrichpresence.

**Comment by nonamethanks** [comment] 2022-12-03 19:26
Ok so, if I add `"enableIdleStatus": "False"` to the storedData.json file then it's able to recognize this setting, however the program seems to be unable to change it. If I set it to True then changing the setting in the program won't do anything.

**Comment by Ombrelin** [comment] 2022-12-03 19:55
Okay, thank you for that feedback. How do you close the software ? By using the "Exit" option on the tray icon or some other way ?

**Comment by nonamethanks** [comment] 2022-12-03 20:17
Yes, I close it exclusively that way.

**Comment by Ombrelin** [comment] 2022-12-25 11:20
I'm sorry I'm still unable to reproduce the issue :(

**Comment by GwnMichael** [comment] 2022-12-26 21:36
Got the same issue , it keeps going back after a restart sadly

**Comment by Ombrelin** [comment] 2023-02-26 18:27
In the next release, I'll introduce special logging to debug this issue.

**Comment by cbtlr** [comment] 2023-03-02 15:42
I can also confirm that the application does not "remember" your choice for the display idle status after closing it and relaunching.

**Comment by Ombrelin** [comment] 2023-03-26 19:44
Logging to troubleshoot this issue has been implemented in last release. Could you reproduce the behaviour and upload me the log in question ? It contains "Saving setting enableIdleStatus to storage with value :"

**Comment by GwnMichael** [comment] 2023-03-26 23:18
I will give it a try tomorrow (if i don’t forgot) , and will let you know if it worked!

**Comment by cbtlr** [comment] 2023-04-14 15:27
This issue persists with the latest release. "Display Idle Status" choice is not retained upon terminating the program.

**Comment by Ombrelin** [comment] 2023-04-14 16:17
Yes I'm aware, as the posts above explain, the thing is I can't reproduce the issue myself. What I introduced in the latest release is logs yo troubleshoot that error. 
Please provide your log file located in the `.plexrichpresence` folder of your home directory, if you'd like to help me investigate.

**Comment by cbtlr** [comment] 2023-04-14 16:21
> Yes I'm aware, as the posts above explain, the thing is I can't reproduce the issue myself. What I introduced in the latest release is logs yo troubleshoot that error. Please provide your log file located in the `.plexrichpresence` folder of your home directory, if you'd like to help me investigate.
[plexrichpresence.zip]

(https://github.com/Ombrelin/plex-rich-presence/files/11234958/plexrichpresence.zip)

Sure. See attached.

**Comment by Ombrelin** [comment] 2023-04-16 07:38
Hi @cbtlr , just had a look at the logs, and they appear normal to my understanding.   
Could you tell me whether the `storedData.json` file (located next to the logs) contains a `enableIdleStatus` key ? Thanks in advance

**Comment by pblivingston** [comment] 2023-05-06 18:01
I am experiencing the same behavior. From a fresh install, I opened the app, chose to log in via browser, entered custom server settings, and closed the app from the tray icon. I did not toggle the Idle message option off. At this point I checked to see that storedData.json does not contain enableIdleStatus. I launched the app again, toggled the Idle message option off, and closed the app from the tray icon. I checked again to see that storedData.json still does not contain enableIdleStatus.

I'm happy to provide any more info you might need.

Log is attached.
[logs2023050613.txt](https://github.com/Ombrelin/plex-rich-presence/files/11413042/logs2023050613.txt)

**Comment by Ombrelin** [comment] 2023-05-29 13:12
Hi @pblivingston, thank you for this detailed report on the app behaviour, this is very helpful.
I'm going to work on the issue in light of the new data to try and fix the problem.

**Comment by pblivingston** [comment] 2023-05-29 16:49
That's great. I'll be keeping an eye on the thread if there's something else I can do to help.

**Comment by Ombrelin** [comment] 2023-06-11 12:32
I can't get my head around this issue :'(   
I'm still not able to reproduce it, and your log shows correctly the log entries I added : "Saving setting enableIdleStatus to storage with value", and with different values, so I guess the issue is not there. 

I have no idea on how to further troubleshoot it, being still unable to reproduce.  
 I'll  try adding more logs in a next release, specifically around the system that writes config to the file, but I have little hope.

**Comment by pblivingston** [comment] 2023-06-11 14:04
That's too bad. At the moment, if I want to change the idle status option, doing so manually in storedData.json and opening/restarting the app is a functional workaround for me. I'll try to keep my eye on future updates and this thread for any developments.

**Comment by lilmac96** [comment] 2023-07-19 19:28
i have the same issue, but after reading this thread i have added the missing string to storedData.json
at the end inside the } i added ,"enableIdleStatus":"false"
(ensure you add a comma after the previous string)

![image](https://github.com/Ombrelin/plex-rich-presence/assets/140013582/b81a395a-fcc6-4130-8a75-b4053753003a)

**Comment by cbtlr** [comment] 2023-07-21 14:18
> 

Manually adding this string also addressed my issue. Is it possible the release version does not include this? Or legacy users are not getting this value added when they reinstall a more recent version?

**Comment by Ombrelin** [comment] 2023-08-15 19:32
Okay so to prevent this issue once and for all, I decided to ditch my custom json based system for a library made for local settings storage called Akavache.  
So hopefully this will not happen anymore.  Will close for now, please re-open if the problem happens again.

**Closed by Ombrelin** 2023-08-15 19:32 UTC
Labels: bug
