### ISSUE TITLE
display bug, not showing any titles only countdown with remaining time

### ISSUE THREAD

**Issue by iurirolho** [Ombrelin/plex-rich-presence#64] opened 2021-10-23 11:44 UTC
![image](https://user-images.githubusercontent.com/20928051/138554372-da99024e-f5e7-4b68-8fd4-64b8e5362dc3.png)![image](https://user-images.githubusercontent.com/20928051/138554534-8677ff25-21f9-49cd-bd6a-30caec8c116a.png)
as shown by both pics detection seems to be working fine but the display in discord is not, attached logs in zip format as well, hopefully you can get down to root of this issue
[discordrichpresencelogs.zip](https://github.com/Ombrelin/plex-rich-presence/files/7402819/discordrichpresencelogs.zip)

**Comment by alexcomo95** [comment] 2021-12-12 04:16
Duplicate of #58

**Comment by Ombrelin** [comment] 2022-01-17 14:16
Closed as duplicate of #58

**Closed by Ombrelin** 2022-01-17 14:16 UTC
