### ISSUE TITLE
plex-rich-presence DOCKER builds for Synology (and more?)

### ISSUE THREAD

**Issue by FloydianSound** [Ombrelin/plex-rich-presence#102] opened 2024-01-17 16:20 UTC
I would love to see this as a docker app

i'm on Synology DSM224+ (DSM7.2) (Linux)
we use the Package Manager and Container Manager (Docker-compose2 basically)

any plans to make a release for this ? would love to uncouple this plug-in from my PC if possible.

**Comment by Ombrelin** [comment] 2024-09-30 20:07
Duplicate of #56

**Closed by Ombrelin** 2024-09-30 20:07 UTC
