### ISSUE TITLE
Can’t find server 

### ISSUE THREAD

**Issue by Josja2030** [Ombrelin/plex-rich-presence#96] opened 2023-04-15 20:07 UTC
Hi, I downloaded your app, is there anything else I need to do? I logged in with my plex details I located my server but neither does private IP details / public work, im not tech savvy so if I’m suppose to do some coding on my part to access the app then that sucks for me lol. I saw an old question 3 weeks ago about having my same issue. Do you have discord?? So I can ask for help or a YouTube video explaining how to set this up? I don’t learn well when reading things I have to see it face to face

**Comment by Ombrelin** [comment] 2023-04-16 07:35
Hi !   
If you selected a server registered on you PLEX account and it can't be connected to, it most likely means that this data record on your PLEX account is outdated. You can check this data on your PLEX account settings, in the PLEX UI.

You can also send me the logs file present in your home directory under the folder `.plexrichpresence` so I can confirm that it's this issue you're facing.

**Comment by Josja2030** [comment] 2023-04-16 08:14
How can I do that bro? I’m not smart with this stuff I’m a mac user but using windows pc.  Do I locate the plexrichpresence file or is there a special code I type in search bar to show u? It would be easier if I added u on discord and we can voice chat n I share my screen? If that’s ok, I want to learn tbh. My discord is ᴛ͢͢͢ʏɢxꜱ 🇦🇺#4031

**Comment by Josja2030** [comment] 2023-04-16 16:25
So now I’m getting “exposed” what does that mean?

**Comment by Josja2030** [comment] 2023-04-16 16:28
Gone back to can’t reach server, idk what I’m doing wrong please help

**Comment by Josja2030** [comment] 2023-04-16 16:28
Make a YouTube video at least bro please

**Comment by Josja2030** [comment] 2023-04-16 16:34
![image](https://user-images.githubusercontent.com/130867663/232326977-1b75c1a7-6def-4c10-9b89-2ee55d707fac.jpg)

Where do I go here to show u my logs ?

**Comment by Josja2030** [comment] 2023-04-18 19:00
Hi could u pls help :)

**Comment by Josja2030** [comment] 2023-05-10 13:11
Hello issue still happening pls help

**Comment by Ombrelin** [comment] 2023-05-29 13:09
Hi @Josja2030,
I'm truly sorry for answering so late, I've  been quite busy lately.

You can find the logs files in the `.plexrichpresence` directory, which in your user directory (`C:/Users/<your windows username>`). If you would rather send them through a private channel for privacy reason, you can send them by email at arsene@lapostolet.fr
When you will have sent those files to me, I'll be able to analyse them in order to understand the issue you are facing.
Thank in advance,

**Comment by Ombrelin** [comment] 2023-06-11 12:15
Closing for now since no feeback, reopen if needed

**Closed by Ombrelin** 2023-06-11 12:15 UTC
