### ISSUE TITLE
Partial Rich Presence Display

### ISSUE THREAD

**Issue by mamokin** [Ombrelin/plex-rich-presence#58] opened 2021-09-11 23:49 UTC
![image](https://user-images.githubusercontent.com/15617310/132966233-81cd6b5b-1801-4a5d-86ed-2d690a355c34.png)
Not sure what is going on here, the logs show the correct track is being detected (music) but the rich presence only shows a time tracker...

~also, subsequent tracks are not being picked up by the app

**Comment by Ombrelin** [comment] 2021-09-20 06:21
That's odd, I'll try to reproduce

**Comment by alexcomo95** [comment] 2021-12-12 04:03
I've found this is happening when the track number is missing from the metadata. The text area fails silently, since it has no alternative way of displaying it. Only way to bring it back is to reload the app. If you add the metadata, don't forget to reload it in Plex.

**Comment by alexcomo95** [comment] 2021-12-12 04:08
This seems like a small change. I'll see if I can find some time to suggest a fix.

**Comment by iurirolho** [comment] 2021-12-12 11:00
hopefully, this gets fixed as this is a bit annoying when the app bugs out because of something like that

**Comment by Ombrelin** [comment] 2022-10-08 13:35
Should be fixed in 2.0 version ! When no metadata, the app should just display an idle session

**Closed by Ombrelin** 2022-10-08 13:35 UTC
Labels: bug
